package uk.gov.hmcts.reform.sandl;
import uk.gov.hmcts.reform.sandl.test.*;
import static uk.gov.hmcts.reform.sandl.model.util.UUIDUtil.uuid;

rule "Init B"
when
then
	System.out.println("--------------------------------- Starting rule engine B.");
end

rule "From B to A"
when
	$b : TestTransactionController.B ( value < 10 )
then
	insertLogical (new TestTransactionController.A ( uuid(), $b.value + 1 ));
	System.out.println("->->-> B to A for " + $b.value + " ->->->->->->->->->->->->");
	System.out.println($b);
end